"""empty message

Revision ID: 635b40a3ef21
Revises: 
Create Date: 2021-04-25 10:17:48.970543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635b40a3ef21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actor', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('Actor', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Actor', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Actor', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Actor', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Actor', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Actor', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('Actor', 'image_url')
    # ### end Alembic commands ###
